### ISSUE TITLE
redirect_uri_mismatch - invalid credentials

### ISSUE THREAD

**Issue by bearded-avenger** [jwickard/omniauth-wordpress-oauth2-plugin#14]
We’ve been banging our heads against the walls on this for nearly two weeks now. We’re running Rails 4, most recent version wp-oauth (wordpress plugin client), devise, omni-auth, and omniauth-wordpress_hosted. We have a rails app, which is authenticating against a WordPress installation. 

I’ve read over everything and am 1000% confident that it’s setup correctly. It’s even behaving correctly: cl.ly/2B1e3K1m0a2a

When I return to the WordPress site, I’m logged in. However the rails app just spits out the same response. The only clue is in the log: cl.ly/2O293j3a3P3o

The redirect URI seems to be setup correctly and matches. http://cl.ly/1l1a331o410q

Are you able to offer any insight? I've reached out to the plugin author and haven't had much luck in that area.

**Comment by bearded-avenger** [comment]
I've finally got this figured out. If anyone wants details on how I pulled it off I"m happy to share.

**Comment by ArkGladios** [comment]
Hey @bearded-avenger could you share the solution?
