### ISSUE TITLE
Should strategy_class in devise.rb be renamed to WordpressHosted in README.md?

### ISSUE THREAD

**Issue by mlwilkerson** [jwickard/omniauth-wordpress-oauth2-plugin#7]
I've been trying to implement this and have run into some problems. One of them seemed to be solved when I change the name of the strategy class in devise.rb. Your instructions still show it as:
`OmniAuth::Strategies::WordpressOauth2Plugin`

This resulted in the following error when running Passenger:
`Message from application: uninitialized constant OmniAuth::Strategies::WordpressOauth2Plugin (NameError)`

This error went away when I edited devise.rb and changed the strategy_class to:
`OmniAuth::Strategies::WordpressHosted`

Does that seem like the proper correction in the code? And if so, should it be updated in the README?

**Comment by jwickard** [comment]
:+1:

**Comment by atzorvas** [comment]
@jwickard still named WordpressOauth2Plugin in the Readme

**Comment by hallmatt** [comment]
Thanks for posting. The Readme needs updating

**Comment by hm-mkim** [comment]
It worked for me after changing it as well.

**Comment by karthickibz** [comment]
Thanks @mlwilkerson, it is working for me :)

**Comment by jwickard** [comment]
Updated the readme.
